### ISSUE TITLE
make all FlexibleContainerOptions's props accept function

### ISSUE THREAD

**Issue by RyanYANG52** [ipikuka/remark-flexible-containers#2]
Right now this plugin's options only has containerProperties and titleProperties is `TPropertyFunction`, it will be nice to change all props to `string | TPropertyFunction`

**user case**
- add fallback title text, if null
- use details summary or div dynamically, like in [vitepress](https://vitepress.dev/guide/markdown#custom-containers)

great work by the way! thanks.

**Comment by talatkuyuk** [comment]
Thank you for reporting the issue.

In order to add a fallback title text, if not defined, I suppose the `title` option could be more useful having a string option like this ->`title: string | null | undefined`. 

Another fallback title option is to be the same with the container type like warning, note, tip etc. For that case I can add a special string option like "type". In that case the `title` option could be `string | "type" | null | undefined` Do you agree ? 

For the details summary container, it is great advice. I see that in the vitepress. I will try to implement it.

**Comment by RyanYANG52** [comment]
In my case, fallback title is capitalised type (`note => Note`) or translate to Chinese chars, maybe I can use css to set `::before` `content`. but if title is a `TPropertyFunction | null | undefined` it can be more flexible and done in compile time

**Comment by talatkuyuk** [comment]
Hi @RyanYANG52,

Sorry for the delay. I added `callback function` options for the the **title**, **tag names**, and **class names** options.

Version 1.0.7 release notes are available [here](https://github.com/ipikuka/remark-flexible-containers/releases).

Could you please have a check the new version? If you satisfies you can close the issue.

For the **details summary** like in [vitepress](https://vitepress.dev/guide/markdown#custom-containers) will be another version, needs to create a separate issue.

**Comment by RyanYANG52** [comment]
works perfectly, thanks. 
code for ref: 
```js
remarkFlexibleContainers,
{
    containerClassName: 'custom-block',
    titleClassName: 'custom-block-title',
    titleTagName: 'p',
    title: (type, title) => {
	    if (title || !type) return title;
	    const typeTitle = typeTitlePresets[type];
	    return typeTitle || title;
    },
},
```

**Comment by talatkuyuk** [comment]
`if (title || !type) return title;` is error-prone logic. If there is no `type`, it is impossible `title` exists.

So if no `type`, the statement `return title;` is going to be always `undefined`.

**Comment by talatkuyuk** [comment]
> use **details summary** or **div** dynamically, like in [vitepress](https://vitepress.dev/guide/markdown#custom-containers)

I figure out that the `remark-flexible-containers` can create `details-summary` HTML element easily with the below options:

```typescript
import remarkFlexibleContainer from "remark-flexible-containers";

use(remarkFlexibleContainer, {
  containerTagName(type) {
    return type === "details" ? "details" : "div";
  },
  containerClassName(type) {
    return type === "details" ? ["remark-details"] : ["remark-container", type ?? ""];
  },
  titleTagName(type) {
    return type === "details" ? "summary" : "div";
  },
  titleClassName(type) {
    return type === "details" ? ["remark-summary"] : ["remark-container-title"];
  },
})
```
If community want me to include this opinionated **"details"** type in to the package, would nice to receive a PR (Pull Request).

**Comment by talatkuyuk** [comment]
> use details summary or div dynamically, like in [vitepress](https://vitepress.dev/guide/markdown#custom-containers)

Hi @RyanYANG52,

I added`<details><summary>` as a feature in **v1.5.0**

All you have to is that you set a specific type **details**.
``` markdown
::: details Title
<!-- content -->
:::
```

```html
<details class="remark-details">
  <summary class="remark-summary">Title</summary>
  <!-- content -->
</details>
```

If you want `<details>` element is opened, add specific identifer **`{@open}`** attribute just after the type `details`.
``` markdown
::: details {@open} Title
<!-- content -->
:::
```
